config/routes.rb
MyAccount::Application.routes.draw do
  resources :gmail_accounts

  devise_for :users

  resources :users
  root :to => 'users#index'

end

app/models/gmail_account.rb
class GmailAccount < ActiveRecord::Base
  attr_accessible :password, :user_id, :username
  belongs_to :user

  def connect
  	Gmail.connect(self.username, self.password)
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :gmail_accounts
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/gmail_accounts_controller.rb
class GmailAccountsController < ApplicationController
  # GET /gmail_accounts
  # GET /gmail_accounts.json
  def index
    @gmail_accounts = GmailAccount.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gmail_accounts }
    end
  end

  # GET /gmail_accounts/1
  # GET /gmail_accounts/1.json
  def show
    @gmail_account = GmailAccount.find(params[:id])
    # a = @gmail_account.connect
    # @gmail_emails = a.inbox.emails(:unread)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gmail_account }
    end
  end

  # GET /gmail_accounts/new
  # GET /gmail_accounts/new.json
  def new
    @gmail_account = GmailAccount.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gmail_account }
    end
  end

  # GET /gmail_accounts/1/edit
  def edit
    @gmail_account = GmailAccount.find(params[:id])
  end

  # POST /gmail_accounts
  # POST /gmail_accounts.json
  def create
    @gmail_account = GmailAccount.new(params[:gmail_account])

    respond_to do |format|
      if @gmail_account.save
        format.html { redirect_to @gmail_account, notice: 'Gmail account was successfully created.' }
        format.json { render json: @gmail_account, status: :created, location: @gmail_account }
      else
        format.html { render action: "new" }
        format.json { render json: @gmail_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /gmail_accounts/1
  # PUT /gmail_accounts/1.json
  def update
    @gmail_account = GmailAccount.find(params[:id])

    respond_to do |format|
      if @gmail_account.update_attributes(params[:gmail_account])
        format.html { redirect_to @gmail_account, notice: 'Gmail account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gmail_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gmail_accounts/1
  # DELETE /gmail_accounts/1.json
  def destroy
    @gmail_account = GmailAccount.find(params[:id])
    @gmail_account.destroy

    respond_to do |format|
      format.html { redirect_to gmail_accounts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gmail_accounts_helper.rb
module GmailAccountsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gmail_accounts/_form.html.erb
<%= form_for(@gmail_account) do |f| %>
  <% if @gmail_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gmail_account.errors.count, "error") %> prohibited this gmail_account from being saved:</h2>

      <ul>
      <% @gmail_account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gmail_accounts/edit.html.erb
<h1>Editing gmail_account</h1>

<%= render 'form' %>

<%= link_to 'Show', @gmail_account %> |
<%= link_to 'Back', gmail_accounts_path %>

app/views/gmail_accounts/index.html.erb
<h1>Listing gmail_accounts</h1>

<table>
  <tr>
    <th>User</th>
    <th>Username</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @gmail_accounts.each do |gmail_account| %>
  <tr>
    <td><%= gmail_account.user_id %></td>
    <td><%= gmail_account.username %></td>
    <td><%= gmail_account.password %></td>
    <td><%= link_to 'Show', gmail_account %></td>
    <td><%= link_to 'Edit', edit_gmail_account_path(gmail_account) %></td>
    <td><%= link_to 'Destroy', gmail_account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Gmail account', new_gmail_account_path %>

app/views/gmail_accounts/new.html.erb
<h1>New gmail_account</h1>

<%= render 'form' %>

<%= link_to 'Back', gmail_accounts_path %>

app/views/gmail_accounts/show.html.erb
<div class="row-fluid">
  <div class="span3">
  	<div class='well'>
  	  <div class="google-header"><b>gmail:</b> perkinpv@gmail.com</div>
  	  <div class="body">
  	  	<p class='from'>
  	  	  from: <b>perkinpv@mail.ru</b>
  	  	</p>
  	  	<p class='subject'>
  	  	  <%= link_to 'Hello World!', 'https://mail.google.com/mail/'%>
  	  	</p>
  	  	<p class='time'>
  	  	  12:56
  	  	</p>
  	  </div>	
  	</div>
  </div>
  <div class="span3">
  	<div class='well'>
  	  <div class="google-header"><b>gmail:</b> perkinpv@gmail.com</div>
  	  <div class="body">
  	  	<p class='from'>
  	  	  from: <b>perkinpv@mail.ru</b>
  	  	</p>
  	  	<p class='subject'>
  	  	  <%= link_to 'Hello World!', 'https://mail.google.com/mail/'%>
  	  	</p>
  	  	<p class='time'>
  	  	  12:56
  	  	</p>
  	  </div>	
  	</div>
  </div>
  <div class="span3">
  	<div class='well'>
  	  <div class="google-header"><b>gmail:</b> perkinpv@gmail.com</div>
  	  <div class="body">
  	  	<p class='from'>
  	  	  from: <b>perkinpv@mail.ru</b>
  	  	</p>
  	  	<p class='subject'>
  	  	  <%= link_to 'Hello World!', 'https://mail.google.com/mail/'%>
  	  	</p>
  	  	<p class='time'>
  	  	  12:56
  	  	</p>
  	  </div>	
  	</div>
  </div>
  <div class="span3">
  	<div class='well'>
  	  <div class="google-header"><b>gmail:</b> perkinpv@gmail.com</div>
  	  <div class="body">
  	  	<p class='from'>
  	  	  from: <b>perkinpv@mail.ru</b>
  	  	</p>
  	  	<p class='subject'>
  	  	  <%= link_to 'Hello World!', 'https://mail.google.com/mail/'%>
  	  	</p>
  	  	<p class='time'>
  	  	  12:56
  	  	</p>
  	  </div>	
  	</div>
  </div>
  <div class="span3">
  	<div class='well'>
  	  <div class="google-header"><b>gmail:</b> perkinpv@gmail.com</div>
  	  <div class="body">
  	  	<p class='from'>
  	  	  from: <b>perkinpv@mail.ru</b>
  	  	</p>
  	  	<p class='subject'>
  	  	  <%= link_to 'Hello World!', 'https://mail.google.com/mail/'%>
  	  	</p>
  	  	<p class='time'>
  	  	  12:56
  	  	</p>
  	  </div>	
  	</div>
  </div>
  <div class="span3">
  	<div class='well'>
  	  <div class="google-header"><b>gmail:</b> perkinpv@gmail.com</div>
  	  <div class="body">
  	  	<p class='from'>
  	  	  from: <b>perkinpv@mail.ru</b>
  	  	</p>
  	  	<p class='subject'>
  	  	  <%= link_to 'Hello World!', 'https://mail.google.com/mail/'%>
  	  	</p>
  	  	<p class='time'>
  	  	  12:56
  	  	</p>
  	  </div>	
  	</div>
  </div>
  <div class="span3">
  	<div class='well'>
  	  <div class="google-header"><b>gmail:</b> perkinpv@gmail.com</div>
  	  <div class="body">
  	  	<p class='from'>
  	  	  from: <b>perkinpv@mail.ru</b>
  	  	</p>
  	  	<p class='subject'>
  	  	  <%= link_to 'Hello World!', 'https://mail.google.com/mail/'%>
  	  	</p>
  	  	<p class='time'>
  	  	  12:56
  	  	</p>
  	  </div>	
  	</div>
  </div>
  <div class="span3">
  	<div class='well'>
  	  <div class="google-header"><b>gmail:</b> perkinpv@gmail.com</div>
  	  <div class="body">
  	  	<p class='from'>
  	  	  from: <b>perkinpv@mail.ru</b>
  	  	</p>
  	  	<p class='subject'>
  	  	  <%= link_to 'Hello World!', 'https://mail.google.com/mail/'%>
  	  	</p>
  	  	<p class='time'>
  	  	  12:56
  	  	</p>
  	  </div>	
  	</div>
  </div>
  <div class="span3">
  	<div class='well'>
  	  <div class="google-header"><b>gmail:</b> perkinpv@gmail.com</div>
  	  <div class="body">
  	  	<p class='from'>
  	  	  from: <b>perkinpv@mail.ru</b>
  	  	</p>
  	  	<p class='subject'>
  	  	  <%= link_to 'Hello World!', 'https://mail.google.com/mail/'%>
  	  	</p>
  	  	<p class='time'>
  	  	  12:56
  	  	</p>
  	  </div>	
  	</div>
  </div>
  <div class="span3">
  	<div class='well'>
  	  <div class="google-header"><b>gmail:</b> perkinpv@gmail.com</div>
  	  <div class="body">
  	  	<p class='from'>
  	  	  from: <b>perkinpv@mail.ru</b>
  	  	</p>
  	  	<p class='subject'>
  	  	  <%= link_to 'Hello World!', 'https://mail.google.com/mail/'%>
  	  	</p>
  	  	<p class='time'>
  	  	  12:56
  	  	</p>
  	  </div>	
  	</div>
  </div>
  <div class="span3">
  	<div class='well'>
  	  <div class="google-header"><b>gmail:</b> perkinpv@gmail.com</div>
  	  <div class="body">
  	  	<p class='from'>
  	  	  from: <b>perkinpv@mail.ru</b>
  	  	</p>
  	  	<p class='subject'>
  	  	  <%= link_to 'Hello World!', 'https://mail.google.com/mail/'%>
  	  	</p>
  	  	<p class='time'>
  	  	  12:56
  	  	</p>
  	  </div>	
  	</div>
  </div>
  <div class="span3">
  	<div class='well'>
  	  <div class="google-header"><b>gmail:</b> perkinpv@gmail.com</div>
  	  <div class="body">
  	  	<p class='from'>
  	  	  from: <b>perkinpv@mail.ru</b>
  	  	</p>
  	  	<p class='subject'>
  	  	  <%= link_to 'Hello World!', 'https://mail.google.com/mail/'%>
  	  	</p>
  	  	<p class='time'>
  	  	  12:56
  	  	</p>
  	  </div>	
  	</div>
  </div>
</div>


<%= link_to 'Edit', edit_gmail_account_path(@gmail_account) %> |
<%= link_to 'Back', gmail_accounts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyAccount</title>
  <link href='http://fonts.googleapis.com/css?family=Raleway:200' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<!-- refactorir this code! Or push it to helper -->
<% if notice %>   
  <p class="notice"><%= notice %></p>
<% end %>
<% if alert %>  
  <p class="alert"><%= alert %></p>
<% end %>  
<div class="container">
  <%= yield %>
</div>


</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>